apiVersion: v1
kind: ConfigMap
metadata:
  name: petstore-tests-config
  namespace: qa
data:
  ENV_PROFILE: "stage"             # dev|stage|prod
  BASE_URL: "https://petstore.swagger.io/v2"
  API_CONSOLE_LOG: "true"
  API_RETRY_MAX: "2"
  ACCEPT_LANG: "en-US"