name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [ dev, stage, prod ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Show Java/Maven versions
        run: |
          java -version
          mvn -version

      - name: Build & test (profile ${{ matrix.env }})
        run: |
          mvn -ntp -P${{ matrix.env }} -Denv=${{ matrix.env }} verify

      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ matrix.env }}
          path: |
            **/target/surefire-reports/**
          if-no-files-found: warn

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.env }}
          path: |
            **/target/allure-results/**
          if-no-files-found: warn