name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [ dev, stage, prod ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Show Java/Maven versions
        run: |
          java -version
          mvn -version

      - name: Build & test (profile ${{ matrix.env }})
        run: mvn -ntp -P${{ matrix.env }} -Denv=${{ matrix.env }} verify

      - name: Build Allure report (profile ${{ matrix.env }})
        if: always()
        run: |
          if [ -d target/allure-results ] && [ "$(ls -A target/allure-results)" ]; then
            mvn -ntp -DskipTests \
              -Dallure.results.directory=target/allure-results \
              -Dallure.report.directory=target/allure-report \
              io.qameta.allure:allure-maven:2.12.0:report
          else
            echo "No Allure results found; skipping report build."
          fi

      - name: Upload Surefire reports (${{ matrix.env }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ matrix.env }}
          path: '**/target/surefire-reports/**'
          if-no-files-found: warn
          retention-days: 7

      - name: Upload Allure results (${{ matrix.env }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.env }}
          path: '**/target/allure-results/**'
          if-no-files-found: warn
          retention-days: 7

      - name: Upload Allure HTML report (${{ matrix.env }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.env }}
          path: '**/target/allure-report/**'
          if-no-files-found: warn
          retention-days: 7

  # Publish Allure HTML to GitHub Pages
  publish-allure:
    if: ${{ always() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    concurrency:
      group: 'pages'
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Allure results (all envs)
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results-*
          path: allure-results
          merge-multiple: true

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.8
        with:
          allure_results: allure-results
          allure_report: allure-report
          keep_reports: 1

      # ✅ Copy to a writable dir and add .nojekyll (avoids permission issues)
      - name: Prepare Pages site
        run: |
          set -euo pipefail
          if [ ! -d "allure-report" ]; then
            echo "No allure-report folder found"; exit 0
          fi
          rm -rf pages-site
          mkdir -p pages-site
          cp -R allure-report/* pages-site/
          touch pages-site/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages-site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}