name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [ dev, stage, prod ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Show Java/Maven versions
        run: |
          java -version
          mvn -version

      - name: Build & test (profile ${{ matrix.env }})
        run: |
          mvn -ntp -P${{ matrix.env }} -Denv=${{ matrix.env }} verify

      # Generate Allure HTML report if results exist
      - name: Generate Allure HTML (profile ${{ matrix.env }})
        run: |
          if [ -d target/allure-results ] && [ "$(ls -A target/allure-results)" ]; then
            mvn -ntp -DskipTests \
              -Dallure.results.directory=target/allure-results \
              -Dallure.report.directory=target/allure-report \
              io.qameta.allure:allure-maven:2.12.0:report
          else
            echo "No Allure results found; skipping HTML generation."
          fi

      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ matrix.env }}
          path: |
            **/target/surefire-reports/**
          if-no-files-found: warn
          retention-days: 7

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.env }}
          path: |
            **/target/allure-results/**
          if-no-files-found: warn
          retention-days: 7

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.env }}
          path: |
            **/target/allure-report/**
          if-no-files-found: warn
          retention-days: 7