name: Publish qa-core

on:
  push:
    tags: [ 'v*' ]           # publish on tag (e.g., v1.0.0)
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write     # required for GitHub Packages deploy
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          server-id: github                 # matches <distributionManagement><repository><id>
          server-username: GITHUB_ACTOR     # auto env
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set project version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          mvn -ntp -q versions:set -DnewVersion=${TAG#v}

      - name: Build & deploy qa-core
        run: |
          mvn -ntp -DskipTests -pl qa-core -am deploy